<a href="https://colab.research.google.com/github/SiweiLuo/DL_with_Python/blob/master/09_up_and_running_with_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from sklearn.datasets import make_blobs
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# create a synthetic dataset
X, y = make_blobs(random_state=0)
# split data and labels into a training and a test set
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
# instantiate a model and fit it to the training set
logreg = LogisticRegression().fit(X_train, y_train)
# evaluate the model on the test set
print("Test set score: {:.2f}".format(logreg.score(X_test, y_test)))

Test set score: 0.88


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [0]:
import numpy as np 
import os 

def reset_graph(seed=42):
  tf.reset_default_graph()
  tf.set_random_seed(seed) 
  np.random.seed(seed) 
  
  
%matplotlib inline 

import matplotlib 
import matplotlib.pyplot as plt 
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

# Where to save the figures
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "tensorflow"

def save_fig(fig_id, tight_layout=True):
    path = os.path.join(fig_id + ".png")
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format='png', dpi=300)

In [0]:
import tensorflow as tf 

reset_graph() 

x = tf.Variable(3,name="x") 
y = tf.Variable(4,name="y") 

f = x*x*y + y +2 



In [6]:
f 

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [7]:
sess = tf.Session() 

sess.run(x.initializer) 
sess.run(y.initializer)
result = sess.run(f) 

print(result) 

42


In [0]:
sess.close() 

In [0]:
with tf.Session() as sess: 
  x.initializer.run()
  y.initializer.run() 
  result = f.eval() 
  
  

In [10]:
result

42

In [0]:
init = tf.global_variables_initializer() 

with tf.Session() as sess: 
  init.run() 
  result = f.eval() 

In [12]:
result 

42

In [0]:
init = tf.global_variables_initializer() 

In [14]:
sess = tf.InteractiveSession() 
init.run()
result = f.eval() 
print(result) 

42


In [15]:
sess.close() 
result 

42

In [0]:
reset_graph() 

In [17]:
x1 = tf.Variable(1) 
x1.graph is tf.get_default_graph() 

True

In [18]:
graph = tf.Graph() 
with graph.as_default():
  x2 = tf.Variable(2) 
  
  
x2.graph is graph 

True

In [19]:
x2.graph is tf.get_default_graph() 

False

In [20]:
w = tf.constant(3) 
x = w+2
y = x+5 
z = x*3 

with tf.Session() as sess: 
  print(y.eval()) 
  print(z.eval()) 

10
15


In [21]:
with tf.Session() as sess: 
  y_val, z_val = sess.run([y,z]) 
  print(y_val) 
  print(z_val)

10
15


In [22]:
import numpy as np 
from sklearn.datasets import fetch_california_housing

reset_graph() 

housing = fetch_california_housing() 
m , n = housing.data.shape

I0708 03:24:42.120626 140292115126144 california_housing.py:114] Downloading Cal. housing from https://ndownloader.figshare.com/files/5976036 to /root/scikit_learn_data


In [0]:
housing_data_plus_bias = np.c_[np.ones((m,1)),housing.data]

x = tf.constant(housing_data_plus_bias,dtype=tf.float32,name="x") 
y = tf.constant(housing.target.reshape(-1,1),dtype=tf.float32,name="y") 
xt = tf.transpose(x) 
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(xt,x)),xt),y)

with tf.Session() as sess: 
  theta_value = theta.eval() 
                  
                 

In [24]:
theta_value

array([[-3.67372932e+01],
       [ 4.37366009e-01],
       [ 9.47520509e-03],
       [-1.08159676e-01],
       [ 6.48537397e-01],
       [-3.84734449e-06],
       [-3.79239232e-03],
       [-4.19136107e-01],
       [-4.32144403e-01]], dtype=float32)

In [25]:
x = housing_data_plus_bias 
y = housing.target.reshape(-1,1) 

theta_numpy = np.linalg.inv(x.T.dot(x)).dot(x.T).dot(y) 

print(theta_numpy) 

[[-3.69419202e+01]
 [ 4.36693293e-01]
 [ 9.43577803e-03]
 [-1.07322041e-01]
 [ 6.45065694e-01]
 [-3.97638942e-06]
 [-3.78654265e-03]
 [-4.21314378e-01]
 [-4.34513755e-01]]


In [26]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression() 
lin_reg.fit(housing.data,housing.target.reshape(-1,1)) 

print(np.r_[lin_reg.intercept_.reshape(-1,1),lin_reg.coef_.T])

print(np.r_[lin_reg.intercept_.reshape(-1,1),lin_reg.coef_.T]) 

[[-3.69419202e+01]
 [ 4.36693293e-01]
 [ 9.43577803e-03]
 [-1.07322041e-01]
 [ 6.45065694e-01]
 [-3.97638942e-06]
 [-3.78654265e-03]
 [-4.21314378e-01]
 [-4.34513755e-01]]
[[-3.69419202e+01]
 [ 4.36693293e-01]
 [ 9.43577803e-03]
 [-1.07322041e-01]
 [ 6.45065694e-01]
 [-3.97638942e-06]
 [-3.78654265e-03]
 [-4.21314378e-01]
 [-4.34513755e-01]]


In [0]:
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler() 
scaled_housing_data = scaler.fit_transform(housing.data) 

scaled_housing_data_plus_bias = np.c_[np.ones((m,1)),scaled_housing_data]

In [29]:
print(scaled_housing_data_plus_bias.mean(axis=0))
print(scaled_housing_data_plus_bias.mean(axis=1))
print(scaled_housing_data_plus_bias.mean())
print(scaled_housing_data_plus_bias.shape)

[ 1.00000000e+00  6.60969987e-17  5.50808322e-18  6.60969987e-17
 -1.06030602e-16 -1.10161664e-17  3.44255201e-18 -1.07958431e-15
 -8.52651283e-15]
[ 0.38915536  0.36424355  0.5116157  ... -0.06612179 -0.06360587
  0.01359031]
0.11111111111111005
(20640, 9)


In [37]:
housing.target
housing.target.shape

(20640,)

In [38]:
housing.target.reshape(-1,1) 
housing.target.shape

(20640,)

In [39]:
housing.target.reshape(1,-1) 

array([[4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]])

In [40]:
housing.target.reshape(-1,1) 

array([[4.526],
       [3.585],
       [3.521],
       ...,
       [0.923],
       [0.847],
       [0.894]])

In [42]:
reset_graph()

n_epochs = 1000 
learning_rate = 0.01 

x = tf.constant(scaled_housing_data_plus_bias,dtype=tf.float32,name="x") 
y = tf.constant(housing.target.reshape(-1,1),dtype=tf.float32,name="y")
theta = tf.Variable(tf.random_uniform([n+1,1],-1.0,1.0,seed=42),name="theta") 
y_pred = tf.matmul(x,theta,name="predictions") 
error = y_pred-y 
mse = tf.reduce_mean(tf.square(error),name="mse") 
gradients = 2/m * tf.matmul(tf.transpose(x),error) 
training_op = tf.assign(theta,theta-learning_rate*gradients) 

init = tf.global_variables_initializer() 

with tf.Session() as sess: 
  sess.run(init) 
  
  for epoch in range(n_epochs):
    if epoch%100 == 0 : 
      print(" Epoch", epoch, "MSE = ",mse.eval())
      
    sess.run(training_op) 
    
  best_theta = theta.eval() 

 Epoch 0 MSE =  9.161542
 Epoch 100 MSE =  0.71450055
 Epoch 200 MSE =  0.56670487
 Epoch 300 MSE =  0.55557173
 Epoch 400 MSE =  0.5488112
 Epoch 500 MSE =  0.5436363
 Epoch 600 MSE =  0.53962904
 Epoch 700 MSE =  0.5365092
 Epoch 800 MSE =  0.5340677
 Epoch 900 MSE =  0.5321473


In [43]:
best_theta 

array([[ 2.0685523 ],
       [ 0.8874027 ],
       [ 0.14401656],
       [-0.3477088 ],
       [ 0.36178362],
       [ 0.00393811],
       [-0.04269556],
       [-0.66145283],
       [-0.6375278 ]], dtype=float32)

In [0]:
reset_graph() 

n_epochs = 1000 
learning_rate = 0.01

x = tf.constant(scaled_housing_data_plus_bias,dtype=tf.float32,name="x")
y = tf.constant(housing.target.reshape(-1,1),dtype=tf.float32,name="y") 
theta = tf.Variable(tf.random_uniform([n+1,1],-1.0,1.0,seed=42),name="theta") 
y_pred = tf.matmul(x,theta,name="predictions")
error = y_pred - y 
mse = tf.reduce_mean(tf.square(error),name="mse") 



In [0]:
gradients = tf.gradients(mse,[theta])[0]

In [47]:
training_op = tf.assign(theta,theta-learning_rate*gradients) 

init = tf.global_variables_initializer() 

with tf.Session() as sess: 
  sess.run(init) 
  
  for epoch in range(n_epochs):
    if epoch%100==0 : 
      print("Epoch",epoch,"MSE = ",mse.eval())
    sess.run(training_op) 
    
  best_theta = theta.eval() 
  
print("Best theta:" ) 
print(best_theta)
           

Epoch 0 MSE =  9.161542
Epoch 100 MSE =  0.7145004
Epoch 200 MSE =  0.56670487
Epoch 300 MSE =  0.55557173
Epoch 400 MSE =  0.5488112
Epoch 500 MSE =  0.5436363
Epoch 600 MSE =  0.53962904
Epoch 700 MSE =  0.5365092
Epoch 800 MSE =  0.5340677
Epoch 900 MSE =  0.5321473
Best theta:
[[ 2.0685525 ]
 [ 0.8874027 ]
 [ 0.14401658]
 [-0.34770882]
 [ 0.36178368]
 [ 0.00393811]
 [-0.04269556]
 [-0.6614528 ]
 [-0.6375277 ]]


In [0]:
def my_func(a,b):
  z = 0 
  for i in range(100):
    z = a*np.cos(z+i)+z*np.sin(b-i)
  return z 



In [49]:
my_func(0.2,0.3) 

-0.21253923284754914

In [0]:
reset_graph() 

a = tf.Variable(0.2,name="a")
b = tf.Variable(0.3,name="b") 
z = tf.constant(0.0,name="z0") 

for i in range(100):
  z = a*tf.cos(z+i) + z * tf.sin(b-i) 
  
grads = tf.gradients(z,[a,b]) 

init = tf.global_variables_initializer() 



In [51]:
with tf.Session() as sess: 
  init.run() 
  print(z.eval()) 
  print(sess.run(grads)) 

-0.21253741
[-1.1388495, 0.19671395]


In [0]:
reset_graph() 

n_epochs = 1000 
learning_rate = 0.01 

x = tf.constant(scaled_housing_data_plus_bias,dtype=tf.float32,name="x") 
y = tf.constant(housing.target.reshape(-1,1),dtype=tf.float32,name="y")
theta = tf.Variable(tf.random_uniform([n+1,1],-1.0,1.0,seed=42),name="theta") 
y_pred = tf.matmul(x,theta,name="predictions") 
error = y_pred-y 
mse = tf.reduce_mean(tf.square(error),name="mse") 


In [0]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate) 
training_op = optimizer.minimize(mse) 

In [55]:
init = tf.global_variables_initializer() 

with tf.Session() as sess: 
  sess.run(init)
  for epoch in range(n_epochs):
    if epoch % 100 == 0: 
      print("Epoch",epoch,"MSE = ",mse.eval()) 
    sess.run(training_op) 
    
  best_theta = theta.eval() 
  
print("Best_theta:") 
print(best_theta) 

Epoch 0 MSE =  9.161542
Epoch 100 MSE =  0.71450055
Epoch 200 MSE =  0.56670487
Epoch 300 MSE =  0.55557173
Epoch 400 MSE =  0.5488112
Epoch 500 MSE =  0.5436363
Epoch 600 MSE =  0.53962904
Epoch 700 MSE =  0.5365092
Epoch 800 MSE =  0.5340677
Epoch 900 MSE =  0.5321473
Best_theta:
[[ 2.0685523 ]
 [ 0.88740265]
 [ 0.14401655]
 [-0.34770873]
 [ 0.3617836 ]
 [ 0.00393811]
 [-0.04269556]
 [-0.6614529 ]
 [-0.6375279 ]]
