<a href="https://colab.research.google.com/github/SiweiLuo/DL_with_Python/blob/master/LSTM_example2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import keras
from keras.models import Sequential
from keras.layers import LSTM, Dense
import numpy as np
from keras.models import Model
from keras import layers


data_dim = 16
timesteps = 8
num_classes = 10

# expected input data shape: (batch_size, timesteps, data_dim)
#model = Sequential()
#model.add(LSTM(32, return_sequences=True,
#               input_shape=(timesteps, data_dim)))  # returns a sequence of vectors of dimension 32
#model.add(LSTM(32, return_sequences=True))  # returns a sequence of vectors of dimension 32
#model.add(LSTM(32))  # return a single vector of dimension 32
#model.add(Dense(10, activation='softmax'))

input_q = keras.Input(shape=(8,16))
x = layers.LSTM(32,return_sequences=True,input_shape=(8,16))(input_q)
x = layers.LSTM(32,return_sequences=True)(x)
x = layers.LSTM(32)(x)
output = layers.Dense(10,activation='softmax')(x)

encoder = Model(input_q,output)


encoder.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

# Generate dummy training data
x_train = np.random.random((1000, timesteps, data_dim))
y_train = np.random.random((1000, num_classes))

# Generate dummy validation data
x_val = np.random.random((100, timesteps, data_dim))
y_val = np.random.random((100, num_classes))

encoder.fit(x_train, y_train,
          batch_size=64, epochs=5,
          validation_data=(x_val, y_val))

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Train on 1000 samples, validate on 100 samples
Epoch 1/5
1000/1000 [==============================] - 3s 3ms/step - loss: 11.4602 - acc: 0.0920 - val_loss: 11.7093 - val_acc: 0.1500
Epoch 2/5
1000/1000 [==============================] - 0s 319us/step - loss: 11.4586 - acc: 0.0860 - val_loss: 11.7062 - val_acc: 0.1100
Epoch 3/5
1000/1000 [==============================] - 0s 312us/step - loss: 11.4580 - acc: 0.0980 - val_loss: 11.7076 - val_acc: 0.0600
Epoch 4/5
1000/1000 [==============================] - 0s 318us/step - loss: 11.4574 - acc: 0.0910 - val_loss: 11.7085 - val_acc: 0.1300
Epoch 5/5
1000/1000 [==============================] - 0s 304us/step - loss: 11.4564 - acc: 0.1150 - val_loss: 11.7057 - val_acc: 0.1100


In [6]:
encoder.predict(x_train)

array([[0.10052437, 0.0998451 , 0.1003031 , ..., 0.09884373, 0.10001633,
        0.10101987],
       [0.09754301, 0.10028058, 0.09912665, ..., 0.10092712, 0.10000385,
        0.10749473],
       [0.10028634, 0.100945  , 0.10182909, ..., 0.09909721, 0.09905107,
        0.10494837],
       ...,
       [0.09758111, 0.09996177, 0.09782647, ..., 0.10091369, 0.10114408,
        0.10678982],
       [0.10022081, 0.101266  , 0.10120483, ..., 0.09920251, 0.09859049,
        0.10296298],
       [0.09724913, 0.10067371, 0.10081992, ..., 0.10048364, 0.10004298,
        0.10618629]], dtype=float32)

In [9]:
encoder.predict(x_train[:1])

array([[0.10052437, 0.0998451 , 0.1003031 , 0.09757815, 0.10113222,
        0.10055798, 0.10017914, 0.09884373, 0.10001633, 0.10101987]],
      dtype=float32)

In [10]:
x_train[:1].shape

(1, 8, 16)

In [11]:
x_train[:1]

array([[[0.33313398, 0.43588656, 0.68666037, 0.50118299, 0.68073622,
         0.02796325, 0.04117974, 0.70448354, 0.93688683, 0.7554944 ,
         0.82250149, 0.01320538, 0.63198795, 0.58620854, 0.04398051,
         0.99446001],
        [0.13042582, 0.63653135, 0.74191513, 0.38992213, 0.15267397,
         0.41248899, 0.44366157, 0.31454476, 0.79233467, 0.98997282,
         0.50382903, 0.48727983, 0.10361963, 0.71468382, 0.52491146,
         0.8971153 ],
        [0.05185426, 0.85280467, 0.80378904, 0.37634676, 0.1092271 ,
         0.2666893 , 0.92962711, 0.87644757, 0.53917057, 0.14748835,
         0.47541779, 0.76113091, 0.91363918, 0.61765574, 0.09019705,
         0.04862749],
        [0.01991219, 0.01786826, 0.14380176, 0.37309542, 0.27711633,
         0.49101491, 0.66978072, 0.33532598, 0.77177777, 0.34509717,
         0.10222004, 0.20051257, 0.45005462, 0.55634   , 0.4816211 ,
         0.59424036],
        [0.26919289, 0.25979671, 0.98005703, 0.74816724, 0.91656545,
         0.1390